# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UITableViewEx02' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UITableViewEx02
  pod 'SnapKit', '5.0.1'
  pod 'Then', '2.6.0'

  target 'UITableViewEx02Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UITableViewEx02UITests' do
    # Pods for testing
  end

end
