# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NavigationBarEx04' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NavigationBarEx04
  pod 'SnapKit', '5.0.1'
  pod 'Then', '2.7.0'

  target 'NavigationBarEx04Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NavigationBarEx04UITests' do
    # Pods for testing
  end

end
